### ISSUE TITLE
6 Devices Ignored

### ISSUE THREAD

**Issue by Jborn4christ** [sibartlett/homebridge-wink3#1]
My Homebridge is ignoring 6 devices. What is odd, is 1 is a leviton switch, which i have another one that is working fine. The other is the devices running through my Wink Relay, and then one of two Nest thermostats.

**Comment by sibartlett** [comment]
It's odd that the plugin is ignoring some of your devices.

I've published a new version of the plugin, with the following improvements:

* Better error handling
* Better logging:
  * When devices are added
  * When devices can't be added, along with the reason (not supported, etc).

Maybe you can try the new version? I really appreciate your help testing this plugin.

**Comment by Jborn4christ** [comment]
I'll give it a try this weekend. I reverted back to v2. I'm thinking I maybe didn't clear my persist/accessory cache prior to setting up v3, which may have impacted the performance.

**Comment by sibartlett** [comment]
Yeah, it may have been persist/accessory cache. I've also fixed a number of bugs over the past 2 weeks.

I'm closing this issue, as I don't think there's anything else I can do here (for now at least). If you try this plugin out again, and run into further problems then please do open another issue.
