### ISSUE TITLE
Offline Devices Not Showing as No Response

### ISSUE THREAD

**Issue by mriksman** [sibartlett/homebridge-wink3#106]
I would have expected if a device is offline (two of my leakSMART sensors are offline, and JSON in Wink@Home shows connection:false) then in Home it should show as 'No Response'...?
But it's not...

**Comment by mriksman** [comment]
Ahh. Simple fix. Need to change AccessoryHelper.js

```
  readAccessory(accessory, get, callback) {
    // First argument is current state
    // Second argument is desired state (merged state)
      const value = get(accessory.context.last_reading, accessory.merged_state);

    if (accessory.context.last_reading.connection)
       callback(null, value);
    else
       callback("no_response");
  }
```

**Comment by jason-klein** [comment]
The fix suggested by @mriksman worked correctly for me as well. See attached PR. Online devices still functioning normally, but bulbs that are offline now show NO RESPONSE. Before I applied this update locally, bulbs that were offline would show ON (100% Brightness).

**Comment by sibartlett** [comment]
Sorry, I am no longer actively maintaining this project. I am no longer using Wink, and do not have the time or resources to dedicate more to ongoing maintenance.
