### ISSUE TITLE
Warning after upgrade to latest. 

### ISSUE THREAD

**Issue by mreassassin** [sibartlett/homebridge-wink3#107]
pi@raspberrypi:~ $ sudo npm install -g homebridge-wink3
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
+ homebridge-wink3@2.0.0

How do I upgrade the socket data flow thing?

Thanks!

**Comment by sibartlett** [comment]
You can ignore the warning for the time-being. I'm waiting for new versions of the following packages to be published:

* `superagent-proxy` (https://github.com/TooTallNate/superagent-proxy/30)
* `pubnub`

**Comment by mreassassin** [comment]
got it.  how do i update to the latest version of wink3?  I'm getting an error trying to open my garage through homekit/homebridge on my chamberlain myq garage opener that's connected to my wink hub.  no luck there, wondering if the update would help  that?

**Comment by sibartlett** [comment]
Control of chamberlain garage openers is no longer supported by wink API, it’s been restricted by chamberlain to only work in the Wink app.

The only way to get it working with HomeKit -  is to purchase the Chamberlain MyQ Home Bridge.

https://www.chamberlain.com/ca/myq®-home-bridge/p/MYQ-G0303-SP

**Comment by sibartlett** [comment]
Sorry, I am no longer actively maintaining this project. I am no longer using Wink, and do not have the time or resources to dedicate more to ongoing maintenance.
