### ISSUE TITLE
Error turning on/off a device - [Wink] Received unknown notification

### ISSUE THREAD

**Issue by christensonautohome** [sibartlett/homebridge-wink3#108]
I'm getting the following error message when turning on/off plugs and switches.  I'm using a generic z-wave plug, generic z-wave switch and GE/Jasco switches.

Generic Plug
>[2018-8-21 00:57:47] [Wink] Received unknown notification: { capabilities: { is_generic: true },
  created_at: 1520813781,
  desired_state: { brightness: 1, powered: false },
  device_manufacturer: 'generic_zwave',
  gang_id: null,
  hidden_at: null,
  hub_id: 'xxxxxx',
  last_reading: 
   { brightness: 1,
     brightness_changed_at: 1532908334.7083778,
     brightness_updated_at: 1534813067.1243725,
     connection: true,
     connection_changed_at: 1531170629.9319305,
     connection_updated_at: 1534813067.1243725,
     desired_brightness_changed_at: 1534808095.2002172,
     desired_brightness_updated_at: 1534812770.2547486,
     desired_powered_changed_at: 1534813067.1684656,
     desired_powered_updated_at: 1534813067.1684656,
     powered: false,
     powered_changed_at: 1534813067.1243725,
     powered_updated_at: 1534813067.1243725 },
  lat_lng: [ null, null ],
  light_bulb_id: '3498227',
  linked_service_id: null,
  local_id: '21',
  locale: 'en_us',
  location: '',
  manufacturer_device_id: null,
  manufacturer_device_model: 'generic_zwave',
  model_name: 'Generic Z-Wave Light Bulb',
  name: 'Office Lamp',
  order: 0,
  primary_upc_code: 'generic_zwave_light_bulb',
  radio_type: 'zwave',
  subscription: 
   { pubnub: 
      { channel: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|light_bulb-3498227|user-xxxxxx',
        subscribe_key: 'sub-c-xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx' } },
  triggers: [],
  units: {},
  upc_code: 'generic_zwave_light_bulb',
  upc_id: '126',
  updated_at: 1520814629,
  user_ids: [ 'xxxxxxx', 'xxxxxx' ],
  uuid: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  nonce: 1000310 }

**Comment by christensonautohome** [comment]
just to add additional comments to this one.... it seems the requests are filled but the HomeKit app is not updated.  Example: when i request on homepod to turn on a light..... the light will turn on (kick out the error) but the HomeKit app doesn't update, so when i look the app or ask Siri if the light is on the response will show the light off.  
Only when I update the status in the app (by switching it on or off) will i get the correct state.

this seems to be happening on all brands of light switches and plugs i own.  it is not specific to GE/Jasco

**Comment by sibartlett** [comment]
Sorry, I am no longer actively maintaining this project. I am no longer using Wink, and do not have the time or resources to dedicate more to ongoing maintenance.
