### ISSUE TITLE
Wink v 3 Crashing

### ISSUE THREAD

**Issue by chasebmcvicker** [sibartlett/homebridge-wink3#12]
I'm getting a 'Cannot set property 'context' of undefined at WinkPlatform.updateDevice error.  It causes HomeBridge to crash about every 18-24 hours.  I'm about to try the new plugin you made and maybe that'll correct.  Otherwise, any idea what this error might be?

**Comment by sibartlett** [comment]
Hi, this sounds like an issue that I already fixed in the latest version. If the crash continues after you update to the latest, can you paste the whole error here? Thanks! :)

**Comment by chasebmcvicker** [comment]
Ok so installing the new plugin worked.  But now when I try to use my siren/strobe it crashes again.  I am running on Raspberry Pi.  Is there a way to post a screenshot here or send you a direct message through github so I can show you the error? Otherwise I'll login on my Pi browser and copy and paste it there.

**Comment by sibartlett** [comment]
You can email me: simon.bartlett@me.com

**Comment by sibartlett** [comment]
This should be fixed in the latest version `1.1.9`

**Comment by chasebmcvicker** [comment]
Cool! I'll try it out!  Any idea why the Wink Relay and Spotter are reporting 0% humidity?
