### ISSUE TITLE
osram color bulbs

### ISSUE THREAD

**Issue by kalel2000** [sibartlett/homebridge-wink3#16]
since i updated from the original plugin to this one, everytime i try to change the color of a bulb it crashes and wont change.

**Comment by sibartlett** [comment]
Is there an error message you can paste here?

**Comment by kalel2000** [comment]
Absolutely.  Here’s what I get.

Jun 03 13:32:46 rpi_homebridge homebridge[785]: [6/3/2017, 1:32:46 PM] [Wink] Received update notification: Crazy Light (light_bulb/2712923)
Jun 03 13:32:47 rpi_homebridge homebridge[785]: [6/3/2017, 1:32:47 PM] [Wink] Received update notification: Crazy Light (light_bulb/2712923)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: /usr/lib/node_modules/homebridge-wink3/src/devices/light_bulb.js:47
Jun 03 13:32:49 rpi_homebridge homebridge[785]: brightness: values.brightness,
Jun 03 13:32:49 rpi_homebridge homebridge[785]: ^
Jun 03 13:32:49 rpi_homebridge homebridge[785]: TypeError: Cannot read property 'brightness' of undefined
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at set (/usr/lib/node_modules/homebridge-wink3/src/devices/light_bulb.js:47:29)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at AccessoryHelper.writeAccessory (/usr/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:98:19)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at emitMany (events.js:127:13)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at Characteristic.emit (events.js:204:7)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:22)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at Array.forEach (native)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:701:8)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at emitMany (events.js:127:13)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at HAPServer.emit (events.js:204:7)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at emitNone (events.js:86:13)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at IncomingMessage.emit (events.js:188:7)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at endReadableNT (_stream_readable.js:975:12)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jun 03 13:32:49 rpi_homebridge homebridge[785]: at process._tickCallback (internal/process/next_tick.js:104:9)
Jun 03 13:32:49 rpi_homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jun 03 13:32:49 rpi_homebridge systemd[1]: Unit homebridge.service entered failed state.
Jun 03 13:32:59 rpi_homebridge systemd[1]: homebridge.service holdoff time over, scheduling restart.
Jun 03 13:32:59 rpi_homebridge systemd[1]: Stopping Node.js HomeKit Server...
Jun 03 13:32:59 rpi_homebridge systemd[1]: Starting Node.js HomeKit Server...
Jun 03 13:32:59 rpi_homebridge systemd[1]: Started Node.js HomeKit Server.

Sent from Mail for Windows 10

**Comment by sibartlett** [comment]
Thanks! I'll try and fix this. Won't be until Monday though.

**Comment by kalel2000** [comment]
That’s perfectly fine.  I can live.  I  just figured you would like to know about it.

Thanks for your hard work

Sent from Mail for Windows 10

**Comment by sibartlett** [comment]
This is fixed in `1.4.1`

**Comment by kalel2000** [comment]
Thank you
