### ISSUE TITLE
Failed to refresh devices error

### ISSUE THREAD

**Issue by JOyo246** [sibartlett/homebridge-wink3#18]
The is the error received when running Homebridge

`Failed to refresh devices. TypeError: Cannot read property 'on' of undefined
    at definition.characteristics.forEach.c (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:74:11)
    at Array.forEach (native)
    at services.forEach.definition (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:65:34)
    at Array.forEach (native)
    at AccessoryHelper.configureAccessoryCharacteristics (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:62:14)
    at AccessoryHelper.configureAccessory (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:43:10)
    at WinkPlatform.addDevice (/usr/local/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:144:26)
    at Array.forEach (native)
    at /usr/local/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:181:13
    at next (native)`

Here's the code of my config.json file

{
  "bridge": {
    "name": "Joseph's HomeBridge",
    "username": "HIDDEN",
    "port": HIDDEN,
    "pin": "031-45-157"
  },
  "description": "This is an example configuration file with all supported devices. You can use this as a   template for creating your own configuration file containing devices you actually own.",
  "platforms": [
    {
      "platform": "IFTTT",
      "name": "IFTTT",
      "makerkey": "HIDDEN",
      "accessories": [
        {
          "name": "Aros",
          "buttons": [
            {
              "caption": "Aros 64",
              "triggerOn": "aros_64",
              "triggerOff": "aros_off"
            },
            {
              "caption": "Aros 68",
              "triggerOn": "aros_68",
              "triggerOff": "aros_off"
            },
            {
              "caption": "Aros 72",
              "triggerOn": "aros_72",
              "triggerOff": "aros_off"
            },
            {
              "caption": "Aros 76",
              "triggerOn": "aros_76",
              "triggerOff": "aros_off"
            },
            {
              "caption": "Aros 80",
              "triggerOn": "aros_80",
              "triggerOff": "aros_off"
            },
            {
              "caption": "Aros",
              "triggerOn": "aros_on",
              "triggerOff": "aros_off"
            }
          ]
        }
      ]
    },
    {
      "platform": "Wink",
      "name": "Wink",
      "client_id": "HIDDEN",
      "client_secret": "HIDDEN",
      "username": "HIDDEN",
      "password": "HIDDEN",
      "hide_groups": [
        "garage_door",
        "binary_switches",
        "cameras",
        "garage_doors",
        "light_bulbs",
        "locks",
        "propane_tanks",
        "shades",
        "sirens",
        "smoke_detectors",
        "thermostats"
      ],
      "direct_access": "false",
      "access_token": "HIDDEN",
      "refresh_token": "HIDDEN"
    }
  ]
}

**Comment by sibartlett** [comment]
Can you try the latest version, `1.4.3`, that I've just published?

**Comment by JOyo246** [comment]
@sibartlett IT WORKED I'm literally in awe! Is there a way I can pay you??

**Comment by sibartlett** [comment]
No need to pay me, I’m glad to know it’s working now :)
