### ISSUE TITLE
GoControl Garage Door controller

### ISSUE THREAD

**Issue by dcgrove** [sibartlett/homebridge-wink3#21]
Does this version allow for control of the go control garage door controller?  The orginal plugin worked, wink2 doesn't, so I am hoping this is the best of both worlds!

**Comment by sibartlett** [comment]
I can only suggest you try it. I haven’t got a GoVontrol garage door opener. If it doesn’t work, I’ll be happy to work with you to get it working,

**Comment by dcgrove** [comment]
So I got your plugin installed.  The opener shows up in homekit, but does
not respond to any commands.  Is there a log file that I can send/post to
help get it working?

**Comment by sibartlett** [comment]
What method of authentication are you using with homebridge-wink3? Client ID/secret username/password or token obtained from Wink.

I've compared the code to the original plugin, and it looks like I've implemented the same functionality - so this might be tricky to figure out.

**Comment by dcgrove** [comment]
I will look at my config.json in the next couple of days and get back to you.  

Thanks!

**Comment by rjmcfadd** [comment]
The GoControl works great with Wink3 for me. I'm using the OAuth Authorization Code.

**Comment by sibartlett** [comment]
@rjmcfadd Nice to hear someone else is using OAuth Authorization Code!

Did you find it easy/hard to setup? I'd love to hear if you have any suggestions to improve the README, to make setup easier for others. If you got any ideas, please open a new issue or email me. Thanks!

**Comment by dcgrove** [comment]
It turns out that I am using the Oauth password grant as outlined in authorization option 2.  I have set up the application on developer.wink.com to gain the preferred oauth codes.  When I get them, I will report back.

Thanks!

**Comment by dcgrove** [comment]
My app got approved and using the oauth credentials fixed my garage door.  The only thing I would change on the README is to explicitly state that the username and password fields are not required for either of the oauth fields.  Thanks for the help!

**Comment by sibartlett** [comment]
README has been updated:

* Explicitly instruct users to not use `username` and `password` when using new oauth creds.
* GoControl garage opener added to the [FAQ](https://github.com/sibartlett/homebridge-wink3#gocontrol-garage-opener-does-not-seem-to-response-to-commands) section.

**Comment by rjmcfadd** [comment]
@sibartlett It was simple to setup, great job on this plugin! I was already using your Wink3 plugin for other stuff so I didn't need to add anything to config.json file. After following the instructions to add the GoControl to wink, I just restarted homebridge and the garage door appeared in the Home app.

**Comment by sibartlett** [comment]
@rjmcfadd I meant, did you find OAuth Authorization Code easy to setup?

Also when you add/remove devices in Wink, the changes will automatically appear in homebridge within an hour - no need to restart unless you're impatient :)

**Comment by rjmcfadd** [comment]
Haha oh okay! Yeah OAuth Authorization was very easy, the instructions you gave work great. The only problem is waiting for approval but it only took about an hour.
