### ISSUE TITLE
Support for Air Conditioners

### ISSUE THREAD

**Issue by tthoma24** [sibartlett/homebridge-wink3#27]
I'd like to see better support for Air Conditioners, including native fan speed. Additionally, I'm wondering why air conditioners are using the thermostat classification in HomeKit instead of using Apple's native Air Conditioner device type. Is there a reason not to make that change?

**Comment by sibartlett** [comment]
I didn't think HomeKit exposes an air conditioner device type?

I'm reading the documentation, and there is either a Thermostat or Air Purifier. I don't think Air Purifier is the correct device classification.

**Comment by tthoma24** [comment]
Hmmmm... are we reading the same documentation? According to https://developer.apple.com/documentation/homekit/air_temperature_humidity_and_water, there is a category type for air conditioner

**Comment by schmittx** [comment]
@sibartlett is correct, there's no air conditioning service available. This plugin and Homebridge are limited to the following services and characteristics ([link](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js)).

**Comment by sibartlett** [comment]
Closing this issue; until Apple explicitly adds air conditioners as a accessory type, it'll have to stay as a thermostat.

**Comment by tthoma24** [comment]
This has been changed. There is now a "Heater Cooler" service type that can also have a fan associated to expose the fan rotation speed characteristic. See section 8.13 of the HAP spec. Any chance we can switch over to using this instead of thermostat?
