### ISSUE TITLE
Outlink shows up as Not Supported in Home.app

### ISSUE THREAD

**Issue by randot** [sibartlett/homebridge-wink3#30]
Under the devices.md, it looks like Quirky Outlinks are supported, and I'm pretty sure I remember it working when I first setup Hombebridge with the original Wink plugin. But I just finished setting it up again with the Wink3 plugin, and my Outlink shows up as Not Supported. Any idea why that may be happening? Thanks!

**Comment by thechrisreese** [comment]
Are you running iOS 11 beta wth this happenign?

**Comment by randot** [comment]
Yes.

**Comment by thechrisreese** [comment]
Log out of Homebridge and update Homebridge. Sadly you will also have to delete all the accessories and cached accessories folder and reset up all of Homebridge for it to be corrected. It was an issue in Homebridge and iOS 11 that has now been fixed. But ones an item is listed as unsupported it won’t work again until you update and completely rebuild Homebridge.

**Comment by sibartlett** [comment]
Thanks for the help @thechrisreese - I didn’t realize the homebridge iOS11 issue has been fixed yet!

**Comment by randot** [comment]
Ok, thanks for the reply. I’ll leave it alone for now - I only use this outlet for the Christmas tree, so I’ll wait until later in the year to make sure any other iOS 11 kinks get worked out before I go to that much trouble. Thanks!

**Comment by sibartlett** [comment]
I'm closing this issue, as I believe it has been resolved.
