### ISSUE TITLE
 ERROR LOADING PLUGIN homebridge-wink3 - SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by smartymanav** [sibartlett/homebridge-wink3#32]
I keep getting an error with homebridge-wink3 plugin. 

0|homebrid | [8/8/2017, 4:40:37 PM] ====================
0|homebrid | [8/8/2017, 4:40:37 PM] ERROR LOADING PLUGIN homebridge-wink3:
0|homebrid | [8/8/2017, 4:40:37 PM] SyntaxError: Unexpected token {
0|homebrid |     at exports.runInThisContext (vm.js:53:16)
0|homebrid |     at Module._compile (module.js:373:25)
0|homebrid |     at Object.Module._extensions..js (module.js:416:10)
0|homebrid |     at Module.load (module.js:343:32)
0|homebrid |     at Function.Module._load (module.js:300:12)
0|homebrid |     at Module.require (module.js:353:17)
0|homebrid |     at require (internal/module.js:12:17)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/dist/WinkPlatform.js:42:19)
0|homebrid |     at Module._compile (module.js:409:26)
0|homebrid |     at Object.Module._extensions..js (module.js:416:10)
0|homebrid |     at Module.load (module.js:343:32)
0|homebrid |     at Function.Module._load (module.js:300:12)
0|homebrid |     at Module.require (module.js:353:17)
0|homebrid |     at require (internal/module.js:12:17)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/dist/index.js:11:21)
0|homebrid |     at Module._compile (module.js:409:26)
0|homebrid | [8/8/2017, 4:40:37 PM] ====================
0|homebrid | [8/8/2017, 4:40:37 PM] Loaded config.json with 0 accessories and 2 platforms.
0|homebrid | [8/8/2017, 4:40:37 PM] ---
0|homebrid | [8/8/2017, 4:40:37 PM] Loading 2 platforms...
0|homebrid | Error: The requested platform 'Wink' was not registered by any plugin.
0|homebrid |     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
0|homebrid |     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
0|homebrid |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
0|homebrid |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebrid |     at Module._compile (module.js:409:26)
0|homebrid |     at Object.Module._extensions..js (module.js:416:10)
0|homebrid |     at Module.load (module.js:343:32)
0|homebrid |     at Function.Module._load (module.js:300:12)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:70:21)
0|homebrid |     at Module._compile (module.js:409:26)
0|homebrid |     at Object.Module._extensions..js (module.js:416:10)
0|homebrid |     at Module.load (module.js:343:32)
0|homebrid |     at Function.Module._load (module.js:300:12)
0|homebrid |     at Function.Module.runMain (module.js:441:10)
0|homebrid |     at startup (node.js:139:18)

**Comment by edgariscoding** [comment]
I'm having the same issue:

![image](http://i.imgur.com/W6oimIP.jpg)

**Comment by sibartlett** [comment]
I think you might need to try a newer version of Node.js - this plugin requires Node.js 6+. I'll update the README to reflect this.

@edgariscoding I see you're using Node.js 5

**Comment by edgariscoding** [comment]
@sibartlett looks like that was the issue, I upgraded to node v8.2.1 and the error went away!

**Comment by smartymanav** [comment]
@sibartlett thanks, i also updated to node 8.2.1 but still see the error when i launch homebridge. Trying a restart..

**Comment by smartymanav** [comment]
restarted, still getting the error: 0|homebrid | [8/9/2017, 1:32:35 PM] ====================
0|homebrid | [8/9/2017, 1:32:35 PM] ERROR LOADING PLUGIN homebridge-wink3:
0|homebrid | [8/9/2017, 1:32:35 PM] SyntaxError: Unexpected token {
0|homebrid |     at exports.runInThisContext (vm.js:53:16)
0|homebrid |     at Module._compile (module.js:373:25)
0|homebrid |     at Object.Module._extensions..js (module.js:416:10)
0|homebrid |     at Module.load (module.js:343:32)
0|homebrid |     at Function.Module._load (module.js:300:12)
0|homebrid |     at Module.require (module.js:353:17)
0|homebrid |     at require (internal/module.js:12:17)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/dist/WinkPlatform.js:42:19)
0|homebrid |     at Module._compile (module.js:409:26)
0|homebrid |     at Object.Module._extensions..js (module.js:416:10)
0|homebrid |     at Module.load (module.js:343:32)
0|homebrid |     at Function.Module._load (module.js:300:12)
0|homebrid |     at Module.require (module.js:353:17)
0|homebrid |     at require (internal/module.js:12:17)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/dist/index.js:11:21)
0|homebrid |     at Module._compile (module.js:409:26)
0|homebrid | [8/9/2017, 1:32:35 PM] ====================

**Comment by davidvanvo** [comment]
@smartymanav can you share your config?

**Comment by smartymanav** [comment]
Actually after several retries, uninstalling/reinstalling node, node-gyp, homebridge and the wink plugin, looks like its working now! Thanks guys..

**Comment by sibartlett** [comment]
I've updated the README with the Node.js version requirement.
