### ISSUE TITLE
Would it be possible to have a comparison table added comparing the three major homebridge-wink plugins and explaining why this one is better?

### ISSUE THREAD

**Issue by edgariscoding** [sibartlett/homebridge-wink3#33]
I'm simply confused now that there's homebridge-wink, homebridge-wink2, and homebridge-wink3. It seems like this one is more actively maintained, but I'm not sure why I should replace my currently working homebridge-wink2.

Thank you.

**Comment by sibartlett** [comment]
Both homebridge-wink and homebridge-wink2 are no longer maintained.

homebridge-wink3 has the following benefits over the previous 2 plugins:

* Supports new OAuth credentials from [developer.wink.com](https://developer.wink.com)
* Push notifications from Wink are more are more resilient 
* Supports more devices:
  * Fans
  * Cameras (motion detecion, security system activation)
  * Water/leak detectors

**Comment by sibartlett** [comment]
I will consider adding a comparison table.

**Comment by edgariscoding** [comment]
Perfect, this pretty much answers my question but yeah, it may be beneficial to explain this with a table to future users.

Thanks for the help, feel free to close this issue.

**Comment by prashidi82** [comment]
Im a bit confused. If we are using the OAuth credentials method (client_id and client_secret), does this mean that we do not have to include the username and password fields to the config.json file?

**Comment by sibartlett** [comment]
@prashidi82 if you're using OAuth credentials obtained from [developer.wink.com](https://developer.wink.com) - you do not need to include username and password in `config.json`.

**Comment by prince82** [comment]
I think i have everything setup correctly but im getting the error plugin not configured error:

[8/23/2017, 12:03:00 AM] Loaded plugin: homebridge-wink3
[8/23/2017, 12:03:00 AM] Registering platform 'homebridge-wink.Wink'
[8/23/2017, 12:03:00 AM] ---
[8/23/2017, 12:03:00 AM] Loaded config.json with 0 accessories and 0 platforms.
[8/23/2017, 12:03:00 AM] ---
[8/23/2017, 12:03:00 AM] Loading 0 accessories...
Load homebridge-wink.Wink
[8/23/2017, 12:03:00 AM] [homebridge-wink.Wink] Plugin not configured.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/23/2017, 12:03:02 AM] Homebridge is running on port 51826.

**Comment by prince82** [comment]
and it obviously does not load any of the items.

BTW, thank you so much for creating this platform.

**Comment by prince82** [comment]
My issue was that I had platform instead of platforms in the config.json

**Comment by sibartlett** [comment]
I'm closing this issue.

The plan is for this plugin to merge with original wink plugin (#51); so I don't think a comparision table is needed.
