### ISSUE TITLE
Chamberlain Garage Error

### ISSUE THREAD

**Issue by davidvanvo** [sibartlett/homebridge-wink3#34]
Homekit picks up the garage status correctly. However, executing a close or open within Homekit throws the below error. Which then temporarily puts the Garage in an Not Responding status.

` Garage Door (garage_door/76543) { position: 1 }
(node:32298) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: this.log is not a function
`

**Comment by sibartlett** [comment]
An error is occurring when updating the garage door, but unfortunately it isn't being logged correctly.

Can you update to 1.5.1? Then we should hopefully get a better error message.

**Comment by sibartlett** [comment]
Also, what method of authentication are you using?

Chamberlain garage doors only work when using [Android Client ID](https://github.com/sibartlett/homebridge-wink3#chamberlain-garage-opener-does-not-seem-to-response-to-commands).

**Comment by davidvanvo** [comment]
@sibartlett well that's a shame. I'm using the preferred method OAuth Authorization Code.

So i'm SOL?

**Comment by sibartlett** [comment]
Unfortunately this is a limitation in the Chamberlain API.

You can switch to [Android Client ID](https://github.com/sibartlett/homebridge-wink3#android-client-id).

You'll need to edit `config.json`
* Remove the `client_id`, `client_secret`, `access_token` and `refresh_token`
* Then add `username` and `password` options instead.

**Comment by davidvanvo** [comment]
Thanks, just updated it and it works now.

**Comment by pelted** [comment]
So based on this, are there any working garage door openers for Wink that work right now? I was about to order one of the MYQ-G0201 or MYQ-G0301-D to get my current opener tied into my home automation setup. Maybe better off just getting a HomeKit based one and skipping the Wink passthrough.

**Comment by sibartlett** [comment]
Yeah, I haven't tried the GoControl garage opener - so am not able to recommend.

I did see that Chamberlain have added native HomeKit support: https://www.chamberlain.com/apple-partnership

**Comment by davidvanvo** [comment]
correct. the myq does not work with homebridge through the wink api. as @sibartlett pointed out, i had to purchase the myq homekit hub.

**Comment by JimBobSD** [comment]
I use GoControl and it works fine with Wink and Homebridge.
