### ISSUE TITLE
REQ: Wink Relay buttons support

### ISSUE THREAD

**Issue by conwaychen** [sibartlett/homebridge-wink3#35]
This fork is great!  Really enjoying it.  Encountered a problem with my Wink Relays:

Not supported by HomeKit: Relay #1's Top Button (button/xxxxx)
[8/12/2017, 10:18:11 PM] [Wink] Not supported by HomeKit: Relay #1's Bottom Button (button/xxxxx)
[8/12/2017, 10:18:11 PM] [Wink] Not supported by HomeKit: PA Relay #2's Top Button (button/xxxxx)
[8/12/2017, 10:18:11 PM] [Wink] Not supported by HomeKit: PA Relay #2's Bottom Button (button/xxxxx)

Looks like this was a feature ultimately implemented within the main trunk (homebridge-wink)?

https://github.com/KraigM/homebridge-wink/issues/3

UPDATE: Looks like it actually is supported (the buttons show up in HomeKit and work) but I still see an error message on startup.

**Comment by sibartlett** [comment]
I think what's you're seeing is this...

The Relay shows up as 4 devices in the Wink API:

* 2 binary switches - the lighting circuits, that the Relay has been wired into
* 2 buttons - the programmable buttons on the front of the Relay (that the user interacts with)

All the Wink homebridge plugins (including this one) support the binary switch functionality. They do not support the latter (the button functionality).

**Comment by TxnBluDvl** [comment]
Ah, that makes sense for why I can still control the lights, but not the shortcuts that are programmed to one of the buttons.  Thanks!

**Comment by sibartlett** [comment]
I'm closing this issue, as I think it is resolved.
