### ISSUE TITLE
Door Locks

### ISSUE THREAD

**Issue by steedferns** [sibartlett/homebridge-wink3#38]
I'm having an issue with door locks (kwikset).

Everything seems fine in the Home App and works.  Locking/Unlocking works as expected.

However, if I tell SIRI to UNLOCK the door, the log shows the plugin is attempting to LOCK the door??  This is happening on all 3 of my locks.

**Comment by steedferns** [comment]
I should also add that Elgato Eve's app is not displaying the locks correctly.  They are listed as an accessory but do not show up in rooms.

**Comment by steedferns** [comment]
I did a bit of debugging.  Under the section of code of LockTargetState, the set value is always 1 when using Siri, but correctly toggles when using the home app between 0 and 1.  I'm not sure why.

**Comment by djmcp** [comment]
I'm having this same problem as well - I can lock/unlock all day long directly from the Home app but Siri never locks/unlocks.  Per the homebridge-wink3 logs, Home app is doing what it is told (to unlock > "locked: false") vs. Siri who is leaving the lock state the same (to unlock > "locked: true"):

"Siri, unlock the front door":
```
[8/25/2017, 7:13:04 PM] [Wink] Sending update: Front Door (lock/170874) { locked: true }
[8/25/2017, 7:13:04 PM] [Wink] Update sent successfully: Front Door (lock/170874)
```

Home app > unlock the front door:
```
[8/25/2017, 7:14:41 PM] [Wink] Sending update: Front Door (lock/170874) { locked: false }
[8/25/2017, 7:14:41 PM] [Wink] Update sent successfully: Front Door (lock/170874)
```

**Comment by rjmcfadd** [comment]
I'm also having this problem now. Siri won't unlock the door but clicking on the button in the home app works.

**Comment by djmcp** [comment]
I unfortunately am using hass.io so the wink plugin is downloaded each time the homebridge starts in hass.io. Any efforts to correct in master?

**Comment by sibartlett** [comment]
@djmcp I'm not familiar with hass.io... but sounds it's either a) an issue with hass.io, or b) intention feature of hass.io (a way to ensure you have the latest plugins installed). Definitely not an issue with the plugin itself - it has no control over whether it is re-installed.

**Comment by sibartlett** [comment]
@rjmcfadd this plugin is using the same logic as you've given in your code samples:

https://github.com/sibartlett/homebridge-wink3/blob/821a5fbb6cfa1a51848be8c4f060e4ad21a0f197/src/devices/lock.js#L36-L40

**Comment by sibartlett** [comment]
I updated my homebridge installation last night, and now my locks have stopped responding to Siri. Seems it’s homebridge that is the issue; not this plugin.

**Comment by rjmcfadd** [comment]
@sibartlett Okay thanks for looking into it. Hopefully it will be fixed soon in homebridge.

**Comment by junior466** [comment]
Just here to report the same issue.

Thanks!

**Comment by junior466** [comment]
@djmcp After running a Homebridge update, everything is back to normal for me.

**Comment by djmcp** [comment]
@junior466 - what version are you running? I’m showing as on the latest - 1.0.3.  Anybody else have this experience?

**Comment by sibartlett** [comment]
This issue was fixed in homebridge 25 days ago (Sept 15).

**Comment by junior466** [comment]
@djmcp - That's definitely not the latest. I am showing  homebridge-wink3@1.5.0 on my system. View releases [https://github.com/sibartlett/homebridge-wink3/releases](here). 

What about your home bridge install? I am on homebridge@0.4.28.
