### ISSUE TITLE
Humidity shows as 0% from Wink Relays

### ISSUE THREAD

**Issue by malonecentral** [sibartlett/homebridge-wink3#39]
Humidity from Wink Relays reporting 0%.

**Comment by rrrrrk** [comment]
That's strange.  Mine always shows 1%

**Comment by malonecentral** [comment]
I think mine showed 1% at one time but I rebuilt the homebridge server using chef so some plugins might have gotten updated and now the Relays show 0%. I don’t think there is the option to hide just the humidity sensors without hiding the temperature sensors as well, is there?

**Comment by djmcp** [comment]
Same problem here as well. Two wink relays, both report Temperature correctly but Humidity for both is always 0%

**Comment by bernesto** [comment]
I have the same problem. Three Wink Relays, all display humidity as 0%.

**Comment by sibartlett** [comment]
I've published an update (1.5.8), which might fix this.

To update to it `npm update -g homebridge-wink3`

**Comment by rrrrrk** [comment]
Works great after that update.  Thanks

**Comment by bernesto** [comment]
Works for me now too.
