### ISSUE TITLE
Leviton Outlet as Outlets_ID

### ISSUE THREAD

**Issue by Jborn4christ** [sibartlett/homebridge-wink3#42]
Any plans to allow to differentiate a levity outlet as such, as opposed to it showing as a light? I tried adding outlets_id to th config, but that didn't work.

**Comment by sibartlett** [comment]
This has been implemented in the latest version.

See the `outlet_ids` option in the documentation here: https://sibartlett.github.io/homebridge-wink3/configuration.html
