### ISSUE TITLE
Fix for unknown switches reporting a lights.

### ISSUE THREAD

**Issue by EricJilot** [sibartlett/homebridge-wink3#43]
If Wink cannot identify a switch it assumes that it is a light bulb. In my case they are Aeon Metered Switches, that wink is setting as a bulb. I'd love to see a way of forcing them to binary switch that they are, within HomeKit at least.

**Comment by siparo** [comment]
It does: read the ReadMe here: https://github.com/sibartlett/homebridge-wink3/blob/master/README.md and the device info list here: https://github.com/sibartlett/homebridge-wink3/blob/master/DEVICES.md

**Comment by EricJilot** [comment]
Ok looking at the log is is registering as a binary switch. In the home app they are showing as binary light switch, not the outlets they are. Both are plugin modules that are connected to appliances (pumps to be specific). Its kind of confusing to have them appear as lights vs electric motor/pump or even outlets.

**Comment by mriksman** [comment]
I have submitted a fix for this #61.
This allows you to specify Outlet or Switch like you do with the `fan_ids`.

**Comment by sibartlett** [comment]
Closing this issue as the fix was merged.
