### ISSUE TITLE
Chamberlain MyQ

### ISSUE THREAD

**Issue by Jborn4christ** [sibartlett/homebridge-wink3#53]
Anyone have any functioning work around? I can get it to work with the chamberlain2 plugin, but it doesn't generate any notifications. I assume it is all screwed up by their home bridge application/hardware.

**Comment by davidvanvo** [comment]
Mine works fine and I didn't have to do anything special. I assume it's working correctly within the Wink App?

**Comment by davidvanvo** [comment]
take a look at this ticket and see if you it applies to you too

https://github.com/sibartlett/homebridge-wink3/issues/34

**Comment by sibartlett** [comment]
I'm closing this ticket. I've documented the limitation concerning Chamberlain.
