### ISSUE TITLE
Changes outside of Home app (Wink/Manual Switch/Sensor) Don't Seem Update

### ISSUE THREAD

**Issue by mriksman** [sibartlett/homebridge-wink3#56]
I'm noticing that updates aren't being pushed out very quickly. If at all.

I have my Home app open on an iPad. And Wink on my iPhone. I make a change on the iPhone in Wink, and it doesn't update on the iPad (Home app) at all. Every so often I see a `[Wink] Received update notification:` log, but it isn't related to the devices I am turning on/off.

I thought with Pubnub, updates are immediate to the Homebridge/Home app? I even force close the Home app and reopen, and it is still not refreshing the devices...?

**Comment by mriksman** [comment]
It's strange...
I see this when I open the door;
`[Wink] Received update notification: Kitchen Balcony (sensor_pod/228049)`
But it doesn't update in the Home app...?

**Comment by schmittx** [comment]
I've been experiencing the same issues for the past few days, sometimes its perfect and other times it'll update once and then nothing. I've tried everything from force closing Wink app, Home app, etc. but nothing seems to help. Most times it goes away after some time (1+ hour).

I will post my logs when I get home later this week.

**Comment by mriksman** [comment]
It appears to have resolved itself. Possible issue with Wink at the time? Everything has been fine the past few weeks.
