### ISSUE TITLE
Smartthings Zigbee Smart Outlet/Plug - Detects as Lightbulb, Should be Outlet

### ISSUE THREAD

**Issue by mriksman** [sibartlett/homebridge-wink3#58]
Similar to issue #57 - if a `light_bulb` is flagged as an outlet, then it should be treated as such. I have a Smartthings Zigbee Smart Outlet, and it detects as a Lightbulb. The same code used in #57 for the `binary_switch` should be used in the `light_bulb.js` file, so that I can manually force this device to an Outlet.

**Comment by sibartlett** [comment]
Fixed in `1.8.2`
