### ISSUE TITLE
Home App Updates Post Change

### ISSUE THREAD

**Issue by thechrisreese** [sibartlett/homebridge-wink3#6]
Putting this here to discuss - 

So this relies on push notifications and doesn't pull updates from Wink? Since there aren't many console.logs I am asking: After I make a change does it poll the API for that hanger? I am noticing the changes are made on Wink but not reflected in the Home app.

**Comment by sibartlett** [comment]
Yes, this is supposed to rely on push notifications. I am experiencing similar issues, so I'll add more logging and debug what's going on.

**Comment by thechrisreese** [comment]
So here is the process I notice - using my Master Bedroom Light -  and where things seem to be breaking 

With Master Light on at 10%
1) Select button to turn light off
2) Button shows light off
3) Button immediately shows light on but light is off
* so it's sending the right signal to Wink but reporting immediately last_reading and displaying that state before desired_state changes in the API
* I also think this is what's breaking automations
4) After a moment Button reflects light is off
* API changed and pushes I assume the new state for mode
5) Select Button to turn light on
6) Button shows light on
7) Button immediately shows light off but light is on
*Again likely displaying last_reading before the API pushes state 
8) After a moment Button reflects light is on but at 100% 
*API push catches the new state for mode
9) After a moment Button reflects light is at 10%
*API push catches the new state for brightness

**Comment by sibartlett** [comment]
Yeah, I think you're on to something here.

What light are you using? Philips Hue? Z-wave? I'm using Lutron Caseta, and this problem isn't so apparent - maybe because they have instant feedback.

**Comment by thechrisreese** [comment]
My bulbs are all Cree Connected

I have a feeling that I needs to report out desired_state for any change until it refreshes Devices

**Comment by thechrisreese** [comment]
I am trying to help with this but I dont know enough about the mapping to be able to edit a file and have things not break.

**Comment by thechrisreese** [comment]
In UpdateAccessoryState I want to try it with desired_state rather than last_reading to see if that stops the behavior.

**Comment by sibartlett** [comment]
Sorry that I've been slow on this. Been at the office all day, and yesterday was Mother's Day.

We could try changing from last_reading to desired_state.

I'm also thinking of adding some dirty checking... Every time a push notification is received, the plugin refreshes the values of ALL accessory characteristics. Instead, I think I should compare the data in the push notification to what was last received, and refresh only those characteristics that have actually changed.

**Comment by thechrisreese** [comment]
I think the issue I am seeing is that before the push notification is received the Home app is receiving information on last_reading so the update looks like it didn't happen for a moment, that throws things off. 

I am also seeing Canary "Arming..." taking a very, very long time. Which I think is blocking other items from also updating.

**Comment by sibartlett** [comment]
The changes that I'm going to make should address the Home app update that happens just before the push notification is received.

**Comment by sibartlett** [comment]
I've published a new version. It should now only send updates to the Home app when actual changes are detected.

**Comment by thechrisreese** [comment]
Ok. Tracking it through tomorrow. Seems like its working and hoping the Automation and Scenes stick now. They seem to be working.

**Comment by sibartlett** [comment]
I've found another issue. The plugin seems to stop receiving push notifications.

**Comment by thechrisreese** [comment]
I am still receiving them and have been since I updated last night. The Automations are still tricky, I have to rework them from Scenes to Devices to see if that fixes it. 

What did you see when the push notifications died?

And the [Receieved Update] I assume means that a push notification came in, not that it was polled? It was the Polling that Wink API timed out for me when I updated WinkV2 to API 2. I assume it is not polling in this version so it must be another reason.

**Comment by thechrisreese** [comment]
I am noticing I have a device that is offiline and it is repeating the push notifications over and over and over again about the device. Not sure if this is because it cant resolve the state?

**Comment by sibartlett** [comment]
The logging still needs further improvements.

It say "Update received" for the following events:

* immediately following a state update
* push notification
* polling (the plugin still polls once an hour)

I'll try amending the logging  to distinguish between those events.

I read somewhere, that you still need to poll once every 1-2 hours to keep the pubnub session active... not sure if that's true. I'll probably try running the plugin with polling fully disabled to see what happens.

**Comment by sibartlett** [comment]
When you say that the device is offline, I suppose you mean "connection" returns false in the API?

**Comment by thechrisreese** [comment]
The bulb is not connecting to Wink right now for some reason. So wink shows it as a device with no connection. I see that that is being polled or pushed (not sure which) every free minutes. I think because it is trying to find the connection and its not being ignored.

**Comment by sibartlett** [comment]
Right, sounds like Wink might be updating the connection timestamp or something on a regular basis? This would trigger a push notification every time.

I don't think this is a cause for concern, but I'll update the logging soon so it's more specific. Probably won't publish a new version until at least tomorrow though.

**Comment by thechrisreese** [comment]
What? You dont have all the free time in the world to publish as many versions as possible at all hours? 

Sounds good. Looks to be holding for me on my side now. And the push are still coming through.

**Comment by sibartlett** [comment]
I've published `1.1.3` with slightly improved logging. The logs now specify when push notifications are received.

**Comment by thechrisreese** [comment]
Thanks I'll check it out.  Things get wonky with trying to make automations work.  I'm thinking about completely re-installing all the accessories to see if that works

**Comment by sibartlett** [comment]
I'm closing this issue. I think all the problems in this issue are solved in the latest version. Any further problems should be reported in new issues.

Thank you so much @thechrisreese, I really appreciate that you took the time to test and report all the problems you ran into!
