### ISSUE TITLE
Ring Doorbell

### ISSUE THREAD

**Issue by ayanm00** [sibartlett/homebridge-wink3#63]
Hi,

I'm planning on buying a Ring Doorbell (Gen. 1) from Best Buy this Black Friday. I would have waited for the Pro to get HomeKit, but they've been saying that for 2 years now, and it still hasn't happened. If I connect the Ring to Wink, will the Doorbell show up on Homebridge through this plugin? If so, does it work as intended? 

By the way, the Ring Doorbell (Gen. 1) is currently on sale at Best Buy for $100.

Thanks!

**Comment by davidvanvo** [comment]
I have the Ring Pro. The only feature you’ll get from the Ring is the Motion Detection. May not seem like much but I’ve been using it to activate my porch lights when it’s night time.
