### ISSUE TITLE
a problem authenticating with Wink

### ISSUE THREAD

**Issue by schristi21** [sibartlett/homebridge-wink3#65]
I am having trouble with getting HomeBridge to auth with wink.  I continue to get the following error.

"There was a problem authenticating with Wink: This client is not permitted to use the password grant type"

Here is my config.json
{
"bridge": {
       "name": "Homebridge",
       "username": "CC:22:3D:E3:CE:30",
       "port": 51826,
       "pin": "031-45-364"
       },

"platforms": [
       {
              "platform": "Wink",
              "name": "Wink",
              "client_id": "{MY_client_id}",
              "client_secret": "{MY_client_secret}",
              "hide_groups": ["sensor_pods", "thermostats"],
              "hide_ids": [],
              "fan_ids": [],
              "direct_access": true
        }
],

"accessories": []
}

I have confirmed that there are no permission issues on the config.json file

any help would be appreciated

-Sean

**Comment by schristi21** [comment]
Further comment, I have tried all 3 auth method in the config and always get the same error.  Also should state that I followed the instructions found in the README to ask for the Client_id and Client_secret to be established.

Thanks

**Comment by kahnartist81** [comment]
following

**Comment by andregaulin** [comment]
Looks like this is happening with the other homebridge-wink plugins as well. I suspect this is due to the recent hub firmware update as I was able to authenticate without an issue before upgrading.

**Comment by sibartlett** [comment]
The built-in client ID and secret (and maybe password grant in general) has now been deprecated by the Wink API.

It seems that going forward, only OAuth Authorization Code authentication will be accepted by the Wink API. So I intend to drop support for the other 2 authentication options in an upcoming update to homebridge-wink3.

**Comment by sibartlett** [comment]
I've published a new version of the plugin (1.7.0), which removes support for Android client ID.

**Comment by sibartlett** [comment]
I've published new documentation here: https://sibartlett.github.io/homebridge-wink3/

Im closing this ticket, but if you're still having issues then feel free to re-open.
