### ISSUE TITLE
ERROR: Could not authenticate with local hub

### ISSUE THREAD

**Issue by davidvanvo** [sibartlett/homebridge-wink3#66]
Everything works fine, but i noticed from time-to-time it'll check to see if my Hub is reachable locally. It'll say it's reachable, but then follows-up with the authentication error:

`Could not authenticate with local hub (Wink Hub 2, 192.168.7.84) { StatusCodeError: 400 - {"data":{"error":"invalid_grant","error_description":""},"errors":["invalid_grant: "],"pagination":{},"error":"invalid_grant","error_description":""}`

It still works fine after this error, but is there anything I can/should do to correct this?

**Comment by kahnartist81** [comment]
I am having the exact same issue, except mine doesn't work at all. Same errors and everything.

**Comment by davidvanvo** [comment]
this error is becoming more frequent. almost every 5min.

**Comment by sibartlett** [comment]
I've got a few reports of this. What method of authentication are you using? OAuth Code?

**Comment by kahnartist81** [comment]
Not to hijack the OPs post, but I was using the generic android credentials, but once the problem started happening, I switched to my own personal ones, but still have the problem. Can't seem to figure out if I even did them correctly or not.

I think my problem is my Redirect URI. I honestly have no idea what to put. Though when I go to that address, I go into the hub 2 XML page, so I think it works. But then none of the access token links work. LOST!
![screen shot 2017-11-21 at 4 30 23 pm](https://user-images.githubusercontent.com/33696994/33103837-af18e944-ced9-11e7-8488-1a1c132b473b.png)

**Comment by kahnartist81** [comment]
Quick update, just retried my OAuth, and was finally able to authenticate it. My config file updated with tokens and such. But everything is still showing as "No Response." But no errors in Terminal.

**Comment by sibartlett** [comment]
Yeah, it seems the built-in Android client ID and secret has now been deprecated by the Wink API.

**Comment by davidvanvo** [comment]
i'm currently using the Android Client ID because of Chamberlain's Garage. Deprecation sounds possible, but not sure why everything still works.

**Comment by sibartlett** [comment]
@davidvanvo it's a possibly that your current install continues to work, because your install already has auth/refresh tokens (it's not trying to re-authenticate using your username/password).

I was testing with the Android client ID yesterday; Wink API refused every one of my authentication requests.

**Comment by kahnartist81** [comment]
I tried the Android ID again too and it failed every time. I got homebridge started and what looks like should be working. But when I go into my Home app on my phone, everything still shows as "No Response." When I use the Wink app, I can see the actions responding in terminal so I know the connection is good. But the Home app still gives me nothing. Do I need to delete the accessories and persist folders?

**Comment by sibartlett** [comment]
@kahnartist81 you might need to remove and re-add the Homebridge accessory in the Home app. If you have trouble re-adding, you can try changing one of the characters in the bridge.username field in config.json

**Comment by sibartlett** [comment]
The Android client ID being deprecated would also explain the constant failures when authenticating with the local hub - as the client ID is required when authenticating with the local hub.

**Comment by sibartlett** [comment]
I've opened a pull request with the changes that I am intending to make: #68

**Comment by davidvanvo** [comment]
thanks @sibartlett.

I updated my code using my OAuth Password Grant. Didn't realize this was possible as I had only tried the OAuth Authorization Code. Not seeing the errors and my Garage appears to be working. So we can definitely assume the Android Client ID is deprecated.

**Comment by davidvanvo** [comment]
i actually spoke too soon. OAuth Password Grant doesnt work with Chamberlain's garage. I guess I'll have to find an alternative approach since Homebridge Wink won't work.

**Comment by sibartlett** [comment]
@davidvanvo I was about to ask whether you were sure about Chamberlain lol

Unfortunately this is a restriction that Chamberlain has placed upon Wink; they will only allow their garage openers to be controlled by the official client IDs :(

**Comment by sibartlett** [comment]
I've published a new version of the plugin (1.7.0), which removes support for Android client ID.
