### ISSUE TITLE
Automations

### ISSUE THREAD

**Issue by thechrisreese** [sibartlett/homebridge-wink3#7]
I'm not sure if it's because of how it's polling for changes, but Automations don't work for me at all.

**Comment by sibartlett** [comment]
Thanks for the heads up. I'll setup some automations and try to reproduce.

**Comment by thechrisreese** [comment]
Ok....for Automations....

I have it set to automate a bunch of devices at different times of the day. Right now Homebridge-Wink3 will start the Automation and run it for the first device in the list and then thats it. It doesnt run the rest of the devices. Not sure if there is a reason. But I have watched it happen over and over again.

**Comment by JimBobSD** [comment]
I am having the same problems with automations as well.  Sends the command to the first device in the automaton - but then does not send the commands to the remaining devices.

**Comment by sibartlett** [comment]
I'll try and reproduce this. I'm away from home until Monday though.

**Comment by sibartlett** [comment]
Good news!

I think I know why this is happening. Funny thing is it just occurred to me out of nowhere while out exploring the Quebec countryside.

Will publish a fix by Monday evening :)

**Comment by sibartlett** [comment]
This should (hopefully) be fixed in the latest version `1.1.9`

**Comment by sibartlett** [comment]
I'm closing this issue as it's fixed in the latest version. If the problem persists then you're welcome to comment here @thechrisreese.
