### ISSUE TITLE
Nest and scenes via Homekit

### ISSUE THREAD

**Issue by dockramer** [sibartlett/homebridge-wink3#71]
Has anyone been able to get scenes working with a Nest thermostat when using only heat?  They seem to work when on Auto (Hot/Cold), but won't work when just on heat.  Was digging around in the thermostat.js files, but can't figure it out.  

I can change the temperature manually, but scenes are part of the simplicity of HomeKit.

Also, I can't set the cooling temp higher than 77 when on Auto...what gives?

Thanks

**Comment by mriksman** [comment]
I had this issue! I could change the temperature with Home manually. I created a scene with only ONE thermostat in it - it worked. As soon as a few more devices were added (lights and such), the thermostat wouldn't change temperature.
I have now removed Nest thermostats from the Wink side of things, and installed the homebridge-nest plugin. Works a treat.

**Comment by sibartlett** [comment]
Closing this issue, given that Nest are ending Wink support.
