### ISSUE TITLE
Wink Relay binary switches with no loads attached 

### ISSUE THREAD

**Issue by mbeck94** [sibartlett/homebridge-wink3#72]
Is there any way to operate the Wink Relay switches as a binary switch without a load being hooked up to the physical unit. I am able to toggle the light in the Home app by pressing the physical switch only when a load is hooked up to the unit. For example, in my bathroom the top switch is wired to the lights and the bottom switch is wired to nothing. I'd like to be able to tap the bottom switch to activate another accessory or scene.

**Comment by mbeck94** [comment]
I believe this is the answer, and this thread can be closed https://github.com/sibartlett/homebridge-wink3/issues/35

**Comment by sibartlett** [comment]
Yep, you found the answer. I'll re-visit this in the future, to see if there's anything we can do.
