### ISSUE TITLE
Clarify authentication instructions

### ISSUE THREAD

**Issue by philfreo** [sibartlett/homebridge-wink3#74]
It says "homebridge-wink3 supports 3 methods of authentication" but then it goes on to only list 2 methods of authentication, unless I'm missing something.

Also, it'd be good to clarify what `<HOMEBRIDGE_IP>` should be, and how that would typically work in a home network.

**Comment by humphreyyy** [comment]
HOMEBRIDGE_IP is the ip of your raspberry pi or whatever device homebridge is running on.

**Comment by sibartlett** [comment]
The plugin did support 3 methods of authentication, until one of them was deprecated. I missed the “3” when updating the README. I’ll get that fixed.

@humphreyyy thank you for explaining HOMEBRIDGE_IP

I intend to improve the documentation/help, it’s just a matter of finding the time.

**Comment by philfreo** [comment]
So you have to have a fixed IP address for your homebridge server? Even with the Wink provided personal client_id/secret that requirement didn't seem to exist in past versions right?

**Comment by sibartlett** [comment]
The IP address is only needed for the initial authentication request.

Wink have changed their API to use OAuth workflow - so now the plugin directs you, the user, to wink.com to authenticate using your username and password, and then Wink will authorize the plugin.

**Comment by humphreyyy** [comment]
So bascially once you‘ve applied for the API with wink.com and you entered the api secret in your config, the plugin will output a link in console that will promt you to login with you wink user name and password. @sibartlett this should maybe be made a bit clearer in the instructions :D I‘m a beginner with homebridge, ssh and linux and this wasn‘t entirely obvious for me and took me a bit to figure out.

**Comment by sibartlett** [comment]
Yes, agreed. I plan to do a better write up with screenshots.

**Comment by humphreyyy** [comment]
Awesome, thank you for your work with this plugin!

**Comment by sibartlett** [comment]
I've updated the README, and have added all new documentation with screenshots!
