### ISSUE TITLE
Client is not authorized or could not be found.

### ISSUE THREAD

**Issue by spartanrob** [sibartlett/homebridge-wink3#76]
Not sure where to turn next.  I've installed Wink3, but when I try to authenticate, I only get:
Client is not authorized or could not be found.
Any help appreciated.

**Comment by sibartlett** [comment]
* Is "Client is not authorized or could not be found" displayed in the log?
* Did you provide `client_id` and `client_secret`  in config.json?

**Comment by spartanrob** [comment]
Yes, it is.

**Comment by sibartlett** [comment]
I would try starting over. Make sure that the following are removed from config.json:

* `username`
* `password`
* `access_token`
* `refresh_token`

And that `client_id` and `client_secret` match those in [developer.wink.com](https://developer.wink.com)
