### ISSUE TITLE
Not permitted to use the password grant type

### ISSUE THREAD

**Issue by neigsti** [sibartlett/homebridge-wink3#84]
I apologize if this is a newbie problem vs. an issue.  I have used Homebridge with Homebridge-Wink for about a year.  Around the holidays when Wink stopped supporting the Android credentials, my homebridge stopped working with Wink.  I have done some research and switched over to Homebridge-Wink3.  I already had a developer account created, so I changed by Client ID and Secret to my own (from Wink) rather than using the Android credentials any longer.  When I try to launch Homebridge, I get the error string at the bottom of this message stating that This client is not permitted to use the password grant type.  

Is there cache or something that I need to delete or refresh?  I have uninstalled the homebridge-wink plugin.  I have also deleted the persist folder and restarted homebridge.  

The snipped from my config.json that contains wink:

"platforms": [{
			"platform": "Wink",
			"name": "Wink",
			"username": "me@myemail.com",
			"password": "mypass",
			"client_id": "MyClientIDFromWINKDeveloper",
			"client_secret": "MyClientSecretFromWINKDeveloper",
			"hide_groups": ["thermostats"],
			"hide_ids": [],
			"fan_ids": []
		}

Error when launching Homebridge:
1/9/2018, 4:16:17 AM] [Wink] Could not authenticate with wink.com { StatusCodeError: 400 - {"data":{"error":"invalid_grant","error_description":"This client is not permitted to use the password grant type"},"errors":["invalid_grant: This client is not permitted to use the password grant type"],"pagination":{},"error":"invalid_grant","error_description":"This client is not permitted to use the password grant type"}
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink3/node_modules/request/request.js:1085:12)
  name: 'StatusCodeError',
  statusCode: 400,
  message: '400 - {"data":{"error":"invalid_grant","error_description":"This client is not permitted to use the password grant type"},"errors":["invalid_grant: This client is not permitted to use the password grant type"],"pagination":{},"error":"invalid_grant","error_description":"This client is not permitted to use the password grant type"}',
  error: 
   { data: 
      { error: 'invalid_grant',
        error_description: 'This client is not permitted to use the password grant type' },
     errors: [ 'invalid_grant: This client is not permitted to use the password grant type' ],
     pagination: {},
     error: 'invalid_grant',
     error_description: 'This client is not permitted to use the password grant type' },
  options: 
   { method: 'POST',
     baseUrl: 'https://api.wink.com',
     uri: '/oauth2/token',
     body: 
      { grant_type: 'password',
        client_id: 'LKFqxrYCqSohE3EEC5YLxE01StisWJ6w',
        client_secret: 'Eh2vfnDHlhz1f1KVgELxB6ax9roIMqGK',
        username: 'neigsti@gmail.com',
        password: 'menotu' },
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.wink.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 323,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.wink.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 323,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
        'content-type': 'application/json; charset=utf-8',
        expires: 'Fri, 01 Jan 1990 00:00:00 GMT',
        pragma: 'no-cache',
        'strict-transport-security': 'max-age=31536000',
        via: '1.1 spaces-router (4e2fbae721c4)',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-request-id': 'da75a169-1f99-a5f3-1e18-8463b2a4c53a',
        'x-runtime': '0.018413',
        'x-xss-protection': '1; mode=block',
        date: 'Tue, 09 Jan 2018 04:16:17 GMT',
        'content-length': '326',
        connection: 'close' },
     rawHeaders: 
      [ 'Cache-Control',
        'no-cache, no-store, max-age=0, must-revalidate',
        'Content-Type',
        'application/json; charset=utf-8',
        'Expires',
        'Fri, 01 Jan 1990 00:00:00 GMT',
        'Pragma',
        'no-cache',
        'Strict-Transport-Security',
        'max-age=31536000',
        'Via',
        '1.1 spaces-router (4e2fbae721c4)',
        'X-Content-Type-Options',
        'nosniff',
        'X-Frame-Options',
        'SAMEORIGIN',
        'X-Request-Id',
        'da75a169-1f99-a5f3-1e18-8463b2a4c53a',
        'X-Runtime',
        '0.018413',
        'X-Xss-Protection',
        '1; mode=block',
        'Date',
        'Tue, 09 Jan 2018 04:16:17 GMT',
        'Content-Length',
        '326',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.wink.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 323,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /oauth2/token HTTP/1.1\r\nhost: api.wink.com\r\naccept: application/json\r\ncontent-type: application/json\r\ncontent-length: 174\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/oauth2/token',
        _ended: true,
        parser: null,
        res: [Circular] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        uri: [Object],
        body: '{"grant_type":"password","client_id":"LKFqxrYCqSohE3EEC5YLxE01StisWJ6w","client_secret":"Eh2vfnDHlhz1f1KVgELxB6ax9roIMqGK","username":"neigsti@gmail.com","password":"menotu"}',
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function: s],
        _rp_reject: [Function: t],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.wink.com',
        path: '/oauth2/token',
        _json: true,
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'https://api.wink.com/oauth2/token',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'api.wink.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 
      { data: [Object],
        errors: [Object],
        pagination: {},
        error: 'invalid_grant',
        error_description: 'This client is not permitted to use the password grant type' } } }

**Comment by neigsti** [comment]
I actually found the answer to my problem by looking at the documentation on a branch of this plugin:

https://www.npmjs.com/package/homebridge-wink3-schmittx

Once I removed the username and password in the configuration options, I was able to authenticate and work successfully.  If this was clear somewhere in the documentation for homebridge-wink3, I must have missed it.  Hopefully this helps save someone else some time...

**Comment by sibartlett** [comment]
Thank you for the feedback. I re-wrote the documentation, but it now assumes you're starting from scratch. I will add a troubleshooting section.

**Comment by neigsti** [comment]
Awesome!  That would be great.  I'm sure there will be others that migrate from the older Homebridge-Wink plugin to your newer plugin now that the Android credentials are no longer supported.  Nice work on the plug-in, by the way!  Works like a champ.
