### ISSUE TITLE
Error: The requested platform 'Wink' was not registered by any plugin.

### ISSUE THREAD

**Issue by jlhunter2008** [sibartlett/homebridge-wink3#92]
After updating to the latest version, I get this error message: Error: The requested platform 'Wink' was not registered by any plugin.

It was working before the update. Any help would be appreciated.

**Comment by sibartlett** [comment]
For this update,

I think you need to upgrade homebridge itself, not just the plugin.

**Comment by christensonautohome** [comment]
I also hade to update my node.js version. You might want to link the full error so people can better help you.
